# Generated by Django 4.2 on 2023-05-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notogri',
            old_name='togri',
            new_name='togri_s',
        ),
    ]
